# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title:
  en: OnyxLabs
  fr: OnyxLabs
email: your-email@domain.com
description:
  en: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  fr: Écrivez une super description de votre nouveau site ici. Vous pouvez modifier cette ligne dans _config.yml. Elle apparaîtra dans la balise meta description (pour les résultats sur Google) et dans le fil RSS feed.xml.
index:
  en: en
  fr: fr
blog:
  en: en/blog
  fr: fr/blog
contact:
  en: en/contact
  fr: fr/contact
download:
  en: en/download
  fr: fr/download
installation:
  en: en/installation
  fr: fr/installation
download_name:
  en: Download
  fr: Téléchargement
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://onyxlabs.fr" # the base hostname & protocol for your site
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: "UA-61108725-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
