# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# jekyll serve --host $IP --port $PORT --baseurl ''
host: 127.0.0.1

port: 4000

# Site settings
title:
  en: OnyxLabs
  fr: OnyxLabs
email: contact@onyxlabs.fr
description:
  en: Onyx is an open source home assistant
  fr: Onyx est un assistant personnel qui gère votre maison.
index:
  en: en
  fr: fr
blog:
  en: en/blog
  fr: fr/blog
contact:
  en: en/contact
  fr: fr/contact
download:
  en: en/download
  fr: fr/download
installation:
  en: en/installation
  fr: fr/installation
installation/skills:
  en: en/installation/skills
  fr: fr/installation/skills
installation/home:
  en: en/installation/home
  fr: fr/installation/home
installation/speak:
  en: en/installation/speak
  fr: fr/installation/speak
download_name:
  en: Download
  fr: Téléchargement
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://onyxlabs.fr" # the base hostname & protocol for your site
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: "UA-61108725-1"

